kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: idp
nodes:
  - role: control-plane
    # Label this node so the ingress controller knows it can run here
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    # Wire the cluster's ports 80/443 straight to your laptop (the host)
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
