apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: podinfo-canary
  namespace: default
spec:
  replicas: 4
  progressDeadlineSeconds: 60
  progressDeadlineAbort: true
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - analysis:
            templates:
              - templateName: podinfo-success-rate
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 75
        - pause: { duration: 30s }
  selector:
    matchLabels:
      app: podinfo-canary
  template:
    metadata:
      labels:
        app: podinfo-canary
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.7.0
          ports:
            - name: http
              containerPort: 9898
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
            initialDelaySeconds: 5
            periodSeconds: 5
